// Generated by CoffeeScript 1.4.0
(function() {

  require(['spanish', 'db', 'scheduler'], function(spanish, db, Scheduler) {
    var app, now;
    now = function() {
      return new Date().getTime() / 1000;
    };
    app = angular.module('myapp', ['ui']);
    app.controller("MainCtrl", function($scope) {
      var allPossibleFeatures, scheduler, setResults, setSchedulerAndResults;
      $scope.verbs = spanish.regularVerbs;
      $scope.showTests = false;
      $scope.logs = [];
      allPossibleFeatures = spanish.allPossibleFeatures();
      scheduler = new Scheduler(allPossibleFeatures);
      $scope.ask = function() {
        var best, ss;
        best = scheduler.best(now());
        $scope.features = best.features;
        ss = spanish.sentences($scope.features);
        if ($scope.features.reverse) {
          $scope.originalLanguage = 'Spanish';
          $scope.targetLanguage = 'English';
        } else {
          $scope.originalLanguage = 'English';
          $scope.targetLanguage = 'Spanish';
        }
        $scope.originalSentence = ss[0];
        $scope.targetSentence = ss[1];
        return $scope.targetShown = false;
      };
      $scope.set = function(h) {
        var key, _results;
        _results = [];
        for (key in h) {
          _results.push($scope[key] = h[key]);
        }
        return _results;
      };
      setResults = function(results) {
        return $scope.logs = results;
      };
      setSchedulerAndResults = function(results) {
        return $scope.$apply(function() {
          var result, _i, _len;
          setResults(results);
          for (_i = 0, _len = results.length; _i < _len; _i++) {
            result = results[_i];
            scheduler.userEvent(JSON.parse(result.properties));
          }
          $scope.benchmark = scheduler.benchmark();
          return $scope.ask();
        });
      };
      $scope.pressed = function(good) {
        var features, result;
        features = $scope.features;
        result = {
          features: $scope.features,
          good: good,
          originalSentence: $scope.originalSentence,
          targetSentence: $scope.targetSentence,
          timestamp: now()
        };
        db.spanishLog(JSON.stringify(result), result.timestamp, setResults);
        scheduler.userEvent(result);
        $scope.benchmark = scheduler.benchmark();
        return $scope.ask();
      };
      return db.showLogs(setSchedulerAndResults);
    });
    return $(function() {
      return angular.bootstrap(document, ["myapp"]);
    });
  });

}).call(this);
